#!/usr/bin/env bash
# This script:
#  Creates the file /var/run/myscript.pid containing its PID
#  Displays "To infinity and beyond" indefinitely.
#  Displays "I hate the kill command" when receiving a SIGTERM signal
#  Displays "Y U no love me?!" when receiving a SIGINT signal
#  Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

# create file
pid_file="/var/run/myscript.pid"
echo $$ > $pid_file

#Infinite loop
x=0
while [ $x -eq 0 ]
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo I hate the kill command' SIGTERM
 trap 'echo "Y U no love me?!"' SIGINT
 trap 'rm pidfile; exit' SIGQUIT
done

