#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
#  With a sleep 2 in between each iteration
#  Displays "I am invincible!!!" when receiving a SIGTERM signal

x=0
while [ $x -eq 0 ]
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo I am invincible!!!' SIGTERM
done
